//! Chrome internationalisation — the "language pack".
//!
//! UI text is looked up through a [`Strings`] table, one `const` per [`Lang`].
//! English is the source of truth; every other language fills the same fields, so
//! the compiler guarantees completeness (a new string can't ship half-translated).
//! Keycaps (`Ctrl+T`), symbols (◉ ⛭ 👓) and proper nouns (FOCUS, GAMBA, MCP,
//! claude/codex) are deliberately NOT translated — only the human-language
//! descriptions and section headers are.
//!
//! Translations here are authored in-house; a native polish pass is recommended
//! before a language is advertised as "supported".

use serde::{Deserialize, Serialize};

/// A UI language. Serialised lowercase into `state.toml` (`lang = "zh"`); an
/// unknown value falls back to English so old/foreign files always load.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Lang {
    #[default]
    En,
    Es,
    De,
    Fr,
    Ru,
    Zh,
    Ja,
    Ko,
    Hi,
}

impl Lang {
    /// Picker order.
    pub const ALL: [Lang; 9] = [
        Lang::En,
        Lang::Es,
        Lang::De,
        Lang::Fr,
        Lang::Ru,
        Lang::Zh,
        Lang::Ja,
        Lang::Ko,
        Lang::Hi,
    ];

    /// The language's own name, shown in the picker (autonym).
    pub fn native(self) -> &'static str {
        match self {
            Lang::En => "English",
            Lang::Es => "Español",
            Lang::De => "Deutsch",
            Lang::Fr => "Français",
            Lang::Ru => "Русский",
            Lang::Zh => "中文",
            Lang::Ja => "日本語",
            Lang::Ko => "한국어",
            Lang::Hi => "हिन्दी",
        }
    }

    /// The language's English name — a fuzzy-search alias (so "german" finds
    /// Deutsch) and a dim subtitle under the autonym in the picker.
    pub fn english(self) -> &'static str {
        match self {
            Lang::En => "English",
            Lang::Es => "Spanish",
            Lang::De => "German",
            Lang::Fr => "French",
            Lang::Ru => "Russian",
            Lang::Zh => "Chinese",
            Lang::Ja => "Japanese",
            Lang::Ko => "Korean",
            Lang::Hi => "Hindi",
        }
    }

    /// The lowercase language code — the third fuzzy-search key (so "de", "zh"
    /// jump straight to a language).
    pub fn code(self) -> &'static str {
        match self {
            Lang::En => "en",
            Lang::Es => "es",
            Lang::De => "de",
            Lang::Fr => "fr",
            Lang::Ru => "ru",
            Lang::Zh => "zh",
            Lang::Ja => "ja",
            Lang::Ko => "ko",
            Lang::Hi => "hi",
        }
    }

    /// This language's string table.
    pub fn strings(self) -> &'static Strings {
        match self {
            Lang::En => &EN,
            Lang::Es => &ES,
            Lang::De => &DE,
            Lang::Fr => &FR,
            Lang::Ru => &RU,
            Lang::Zh => &ZH,
            Lang::Ja => &JA,
            Lang::Ko => &KO,
            Lang::Hi => &HI,
        }
    }
}

/// Every translatable chrome string, grouped by where it appears. Add a field
/// here and the compiler forces every language below to supply it.
pub struct Strings {
    // ── brand · the app name, translated (shared with the /global kiosk) ──
    pub brand: &'static str,
    // ── help modal · frame ──
    pub help: &'static str,
    pub shortcuts: &'static str,
    pub features: &'static str,
    pub demo_btn: &'static str,
    pub demo_sub: &'static str,
    pub help_footer: &'static str,
    // ── help modal · section headers ──
    pub s_tabs: &'static str,
    pub s_edit: &'static str,
    pub s_links: &'static str,
    pub s_scroll: &'static str,
    pub s_look: &'static str,
    pub s_agents: &'static str,
    pub s_window: &'static str,
    pub s_feat: &'static str,
    pub s_theming: &'static str,
    pub s_crt: &'static str,
    pub s_amcp: &'static str,
    // ── shortcuts view · descriptions ──
    pub new_tab: &'static str,
    pub switch_tabs: &'static str,
    pub move_tab: &'static str,
    pub split: &'static str,
    pub move_focus: &'static str,
    pub drag_subtab: &'static str,
    pub rclick_tab: &'static str,
    pub rclick: &'static str,
    pub copy_paste: &'static str,
    pub cut: &'static str,
    pub find: &'static str,
    pub find_all: &'static str,
    pub select_wl: &'static str,
    pub newline: &'static str,
    pub open_link: &'static str,
    pub scroll_hist: &'static str,
    pub clear_scroll: &'static str,
    pub themes_wheel: &'static str,
    pub display_tray: &'static str,
    pub text_size: &'static str,
    pub warp: &'static str,
    pub jump_msg: &'static str,
    pub nav_msg: &'static str,
    pub focus: &'static str,
    pub focus_inherit: &'static str,
    pub pan_focus: &'static str,
    pub input_colour: &'static str,
    pub bell: &'static str,
    pub mcp: &'static str,
    pub new_window: &'static str,
    // ── features view · descriptions ──
    pub f_tiling: &'static str,
    pub f_groups: &'static str,
    pub f_drag: &'static str,
    pub f_rename: &'static str,
    pub f_popout: &'static str,
    pub f_themes: &'static str,
    pub f_perpane: &'static str,
    pub f_wheel: &'static str,
    pub f_grade: &'static str,
    pub f_warp: &'static str,
    pub f_scan: &'static str,
    pub f_crawl: &'static str,
    pub f_gamba: &'static str,
    pub f_detect: &'static str,
    pub f_focus: &'static str,
    pub f_restore: &'static str,
    pub f_mcp: &'static str,
    // ── shared scope labels (theme panel + DISPLAY tray) ──
    pub scope_pane: &'static str,
    pub scope_outer: &'static str,
    pub follow_outer: &'static str,
    // ── DISPLAY (monitor-OSD) tray ──
    pub d_display: &'static str,
    pub g_text_size: &'static str,
    pub g_brightness: &'static str,
    pub g_contrast: &'static str,
    pub g_colour: &'static str,
    pub g_text: &'static str,
    pub g_background: &'static str,
    pub g_gamma: &'static str,
    pub g_menu_bar: &'static str,
    pub g_warp: &'static str,
    pub d_reset: &'static str,
    pub d_roll: &'static str,
    pub d_roll_spd: &'static str,
    pub d_roll_size: &'static str,
    pub d_roll_reset: &'static str,
    pub d_crawl_hdr: &'static str,
    pub d_crawl_on: &'static str,
    pub d_crawl_off: &'static str,
    pub d_angle: &'static str,
    pub d_depth: &'static str,
    // ── help modal · LEFT column affordance labels (bare keycaps stay English) ──
    pub k_alt_arrows: &'static str,
    pub k_drag_subtab: &'static str,
    pub k_rclick_tab: &'static str,
    pub k_rclick: &'static str,
    pub k_dbl_click: &'static str,
    pub k_shift_ctrl_click: &'static str,
    pub k_scroll_wheel: &'static str,
    pub k_theme_icon: &'static str,
    pub k_display_tray: &'static str,
    pub k_text_size_key: &'static str,
    pub k_warp_dial: &'static str,
    pub k_pane_header: &'static str,
    pub k_focus_inherit_key: &'static str,
    pub k_wheel_key: &'static str,
    pub k_input_colour: &'static str,
    pub k_bell_finish: &'static str,
    pub k_mother_bar: &'static str,
    pub kf_tiling: &'static str,
    pub kf_groups: &'static str,
    pub kf_drag: &'static str,
    pub kf_rename: &'static str,
    pub kf_popout: &'static str,
    pub kf_themes: &'static str,
    pub kf_perpane: &'static str,
    pub kf_wheel: &'static str,
    pub kf_grade: &'static str,
    pub kf_warp: &'static str,
    pub kf_scan: &'static str,
    pub kf_crawl: &'static str,
    pub kf_restore: &'static str,
    pub kf_mcp: &'static str,
    // ── theme panel ──
    pub t_theme: &'static str,
    pub t_wheel: &'static str,
    pub t_program: &'static str,
    pub t_syntax: &'static str,
    pub cm_ansi: &'static str,
    pub cm_mono: &'static str,
    pub cm_theme: &'static str,
    pub sc_off: &'static str,
    pub sc_code: &'static str,
    pub sc_agentic: &'static str,
    pub sc_logs: &'static str,
    pub sc_mark: &'static str,
    // ── MCP control panel ──
    pub m_control: &'static str,
    pub m_read_only: &'static str,
    pub m_read_write: &'static str,
    pub m_server_on: &'static str,
    pub m_server_off: &'static str,
    pub m_expose: &'static str,
    pub exp_agents: &'static str,
    pub exp_all: &'static str,
    pub m_events_on: &'static str,
    pub m_events_off: &'static str,
    pub m_writes_on: &'static str,
    pub m_writes_off: &'static str,
    pub m_theme_on: &'static str,
    pub m_theme_off: &'static str,
    pub m_no_panes: &'static str,
    pub m_exposed: &'static str,
    pub m_watches: &'static str,
    pub m_transport: &'static str,
    // ── theme picker names (gamba stays a coined brand) ──
    pub thm_quiet: &'static str,
    pub thm_field: &'static str,
    pub thm_tactical: &'static str,
    pub thm_hacker: &'static str,
    pub thm_gamba: &'static str,
    pub thm_custom: &'static str,
    // ── feature names: localized per Parker's note (👓 lens/loupe, 🎰 slot) ──
    pub focus_name: &'static str,
    pub gamba_name: &'static str,
    // ── mother bar + status bar (front-facing chrome; TERMINAL DELIGHT name TBD) ──
    pub ch_split: &'static str,
    pub ch_sub_terminal: &'static str,
    pub st_tab: &'static str,
    pub st_tabs: &'static str,
    pub st_pane: &'static str,
    pub st_panes: &'static str,
    pub ch_ready: &'static str,
    pub ph_live: &'static str,
    pub ph_exited: &'static str,
    pub ph_done: &'static str,
    pub ph_shell: &'static str,
    pub ph_remote: &'static str,
    // ── 🪦 dead-agents dashboard + recover tool (claude/codex stay brand) ──
    pub dead_agents: &'static str,
    pub resurrect: &'static str,
    pub recoverable: &'static str,
    pub dead: &'static str,
    pub no_recoverable: &'static str,
    pub dead_hint: &'static str,
}

use std::sync::atomic::{AtomicUsize, Ordering};
/// Index into [`Lang::ALL`] of the active UI language, mirrored process-wide so
/// panes — which render themselves without a workspace handle — can localise
/// their own header/status chrome. The workspace republishes it each frame.
static CURRENT: AtomicUsize = AtomicUsize::new(0);

/// Publish the active language (called from the workspace render).
pub fn set_current(l: Lang) {
    let i = Lang::ALL.iter().position(|&x| x == l).unwrap_or(0);
    CURRENT.store(i, Ordering::Relaxed);
}

/// The active language, for code with no workspace handle (e.g. a pane header).
pub fn current() -> Lang {
    Lang::ALL[CURRENT.load(Ordering::Relaxed).min(Lang::ALL.len() - 1)]
}

/// English — the source of truth. Strings match the original inline literals.
pub const EN: Strings = Strings {
    brand: "TERMINAL DELIGHT",
    help: "HELP",
    shortcuts: "SHORTCUTS",
    features: "FEATURES",
    demo_btn: "Spin up a demo of this layout",
    demo_sub: "opens a new window cloning this exact layout, every pane filled with lorem-ipsum — safe to screen-share",
    help_footer: "Esc or click outside to close · themes are live-editable TOML while it runs",
    s_tabs: "TABS & PANES",
    s_edit: "EDITING & CLIPBOARD",
    s_links: "LINKS",
    s_scroll: "SCROLLBACK",
    s_look: "LOOK & FEEL",
    s_agents: "AGENTS · claude / codex",
    s_window: "WINDOW",
    s_feat: "PANES · TABS · WINDOW",
    s_theming: "THEMING",
    s_crt: "CRT · MOTION",
    s_amcp: "AGENTS · MCP",
    new_tab: "New tab",
    switch_tabs: "Switch tabs",
    move_tab: "Move tab (in / across groups)",
    split: "Split ↔ / ↕",
    move_focus: "Move focus between panes",
    drag_subtab: "Move / split · drag out = new window",
    rclick_tab: "Rename · colour · group",
    rclick: "Copy · Paste · Open link · Clear",
    copy_paste: "Copy / Paste",
    cut: "Cut selection (deletes on the input line)",
    find: "Find in this pane (fuzzy) — ↵ jumps to it",
    find_all: "Find across ALL panes (fuzzy)",
    select_wl: "Select word / line",
    newline: "Newline (multiline in claude/codex)",
    open_link: "Open a URL or file path",
    scroll_hist: "Scroll history",
    clear_scroll: "Clear scrollback (not Ctrl+L)",
    themes_wheel: "DESIGN — Themes & colour wheel",
    display_tray: "GAUGES — Monitor grade · text size · text-crawl",
    text_size: "Text size",
    warp: "Curve the glass (0 = flat → fishbowl)",
    jump_msg: "Jump to your previous / next message",
    nav_msg: "Same — navigate your own messages",
    focus: "FOCUS — mirror this pane big",
    focus_inherit: "Reader curves + glares like its pane",
    pan_focus: "Pan a zoomed FOCUS read down / sideways",
    input_colour: "Your turns stand out (👤 wheel pip)",
    bell: "Pane shows ● done + a per-agent sound",
    mcp: "MCP — read-only agent-watch surface",
    new_window: "New window (quick scratch)",
    f_tiling: "Splits divide only the focused pane",
    f_groups: "Colour band · handle chip · collapse pill",
    f_drag: "Split, move, or tear off a new window",
    f_rename: "Caret, selection, word-nav on tab names",
    f_popout: "Quick window · single-instance aware",
    f_themes: "Live-editable TOML, ~300ms hot reload",
    f_perpane: "Theme & grade inherit · 'follow outer'",
    f_wheel: "3 markers — seed · text · complement",
    f_grade: "Bright/contrast/colour/text/bg/gamma + size",
    f_warp: "GPU curve · 0→1.5 dial · per-pane",
    f_scan: "Vignette · phosphor · tracking · jiggle",
    f_crawl: "Star-Wars perspective recede (angle · depth)",
    f_gamba: "Slot machine spins while an agent thinks",
    f_detect: "Detected · jump messages · done bell",
    f_focus: "Mirror a pane big over a frosted blur",
    f_restore: "Crash / quit → resume the exact chat",
    f_mcp: "Read-only watch + push · stdio, never TCP",
    scope_pane: "THIS PANE",
    scope_outer: "OUTER",
    follow_outer: "follow outer",
    d_display: "GAUGES",
    g_text_size: "text size",
    g_brightness: "brightness",
    g_contrast: "contrast",
    g_colour: "colour",
    g_text: "text",
    g_background: "background",
    g_gamma: "gamma",
    g_menu_bar: "menu bar",
    g_warp: "warp",
    d_reset: "reset",
    d_roll: "roll",
    d_roll_spd: "roll spd",
    d_roll_size: "roll size",
    d_roll_reset: "roll → per-theme",
    d_crawl_hdr: "TEXT CRAWL",
    d_crawl_on: "crawl on",
    d_crawl_off: "crawl off",
    d_angle: "angle",
    d_depth: "depth",
    k_alt_arrows: "Alt + arrows",
    k_drag_subtab: "drag a sub-tab",
    k_rclick_tab: "right-click a tab",
    k_rclick: "right-click",
    k_dbl_click: "double / triple-click",
    k_shift_ctrl_click: "Shift- or Ctrl-click",
    k_scroll_wheel: "scroll wheel",
    k_theme_icon: "theme icon (top-right)",
    k_display_tray: "GAUGES tray",
    k_text_size_key: "A──A · Ctrl+wheel",
    k_warp_dial: "warp dial",
    k_pane_header: "(pane header)",
    k_focus_inherit_key: "FOCUS · Inherit theme",
    k_wheel_key: "wheel / shift+wheel",
    k_input_colour: "your input colour",
    k_bell_finish: "bell on finish",
    k_mother_bar: "(mother bar)",
    kf_tiling: "Tiling tree",
    kf_groups: "Tab groups",
    kf_drag: "Drag a sub-tab",
    kf_rename: "Rich rename",
    kf_popout: "Pop-out scratch",
    kf_themes: "4 themes + custom",
    kf_perpane: "Per-pane look",
    kf_wheel: "Colour wheel",
    kf_grade: "Monitor grade",
    kf_warp: "Barrel warp",
    kf_scan: "Scanlines · glow",
    kf_crawl: "Text-crawl",
    kf_restore: "Session restore",
    kf_mcp: "MCP server",
    t_theme: "DESIGN",
    t_wheel: "WHEEL · drag a pip out · ◉ seed T text C comp",
    t_program: "PROGRAM COLOUR",
    t_syntax: "SYNTAX",
    cm_ansi: "ansi",
    cm_mono: "mono",
    cm_theme: "theme",
    sc_off: "off",
    sc_code: "code",
    sc_agentic: "agentic",
    sc_logs: "logs",
    sc_mark: "mark",
    m_control: "CONTROL",
    m_read_only: "READ ONLY",
    m_read_write: "READ + WRITE",
    m_server_on: "server enabled",
    m_server_off: "server disabled",
    m_expose: "expose:",
    exp_agents: "agents only",
    exp_all: "all panes",
    m_events_on: "stream tool-call events",
    m_events_off: "events off",
    m_writes_on: "writes on · agents can restyle",
    m_writes_off: "writes off · read-only",
    m_theme_on: "theme · on",
    m_theme_off: "theme · off",
    m_no_panes: "no panes",
    m_exposed: "pane(s) exposed",
    m_watches: "watches agent panes · never writes to a PTY",
    m_transport: "live server transport: next increment",
    thm_quiet: "quiet",
    thm_field: "field",
    thm_tactical: "tactical",
    thm_hacker: "hacker",
    thm_gamba: "gamba",
    thm_custom: "custom",
    focus_name: "FOCUS",
    gamba_name: "GAMBA",
    ch_split: "split",
    ch_sub_terminal: "SUB-TERMINAL",
    st_tab: "tab",
    st_tabs: "tabs",
    st_pane: "pane",
    st_panes: "panes",
    ch_ready: "READY",
    ph_live: "live",
    ph_exited: "exited",
    ph_done: "done",
    ph_shell: "SHELL",
    ph_remote: "REMOTE",
    dead_agents: "DEAD AGENTS",
    resurrect: "RESURRECT",
    recoverable: "recoverable",
    dead: "dead",
    no_recoverable: "No recoverable agents \u{2014} every saved session is either live or already gone.",
    dead_hint: "click a row to resurrect it \u{2014} or \u{2b07} .cdx to harvest its context into a portable package",
};

/// Español.
pub const ES: Strings = Strings {
    brand: "DELEITE TERMINAL",
    help: "AYUDA",
    shortcuts: "ATAJOS",
    features: "FUNCIONES",
    demo_btn: "Abrir una demo de esta disposición",
    demo_sub: "abre una ventana nueva que clona esta disposición, cada panel lleno de texto de relleno — seguro para compartir pantalla",
    help_footer: "Esc o clic fuera para cerrar · los temas son TOML editable en vivo mientras corre",
    s_tabs: "PESTAÑAS Y PANELES",
    s_edit: "EDICIÓN Y PORTAPAPELES",
    s_links: "ENLACES",
    s_scroll: "HISTORIAL",
    s_look: "ASPECTO",
    s_agents: "AGENTES · claude / codex",
    s_window: "VENTANA",
    s_feat: "PANELES · PESTAÑAS · VENTANA",
    s_theming: "TEMAS",
    s_crt: "CRT · MOVIMIENTO",
    s_amcp: "AGENTES · MCP",
    new_tab: "Nueva pestaña",
    switch_tabs: "Cambiar de pestaña",
    move_tab: "Mover pestaña (dentro / entre grupos)",
    split: "Dividir ↔ / ↕",
    move_focus: "Mover el foco entre paneles",
    drag_subtab: "Mover / dividir · arrastrar fuera = ventana nueva",
    rclick_tab: "Renombrar · color · grupo",
    rclick: "Copiar · Pegar · Abrir enlace · Limpiar",
    copy_paste: "Copiar / Pegar",
    cut: "Cortar selección (borra en la línea de entrada)",
    find: "Buscar en este panel (difuso) — ↵ salta a él",
    find_all: "Buscar en TODOS los paneles (difuso)",
    select_wl: "Seleccionar palabra / línea",
    newline: "Salto de línea (multilínea en claude/codex)",
    open_link: "Abrir una URL o ruta de archivo",
    scroll_hist: "Desplazar el historial",
    clear_scroll: "Limpiar el historial (no Ctrl+L)",
    themes_wheel: "DESIGN — Temas y rueda de color",
    display_tray: "GAUGES — Ajuste del monitor · tamaño de texto · text-crawl",
    text_size: "Tamaño del texto",
    warp: "Curva el cristal (0 = plano → pecera)",
    jump_msg: "Salta a tu mensaje anterior / siguiente",
    nav_msg: "Igual — navega tus propios mensajes",
    focus: "LENTE — refleja este panel en grande",
    focus_inherit: "El lector se curva y brilla como su panel",
    pan_focus: "Desplaza una lectura LENTE ampliada abajo / a los lados",
    input_colour: "Tus turnos resaltan (pip 👤 de la rueda)",
    bell: "El panel muestra ● listo + un sonido por agente",
    mcp: "MCP — superficie de observación de agentes, solo lectura",
    new_window: "Nueva ventana (borrador rápido)",
    f_tiling: "Las divisiones afectan solo al panel enfocado",
    f_groups: "Banda de color · ficha de asa · píldora de colapso",
    f_drag: "Divide, mueve o desprende una ventana nueva",
    f_rename: "Cursor, selección y navegación por palabras en los nombres",
    f_popout: "Ventana rápida · consciente de instancia única",
    f_themes: "TOML editable en vivo, recarga en ~300ms",
    f_perpane: "Tema y ajuste se heredan · «seguir exterior»",
    f_wheel: "3 marcadores — semilla · texto · complemento",
    f_grade: "Brillo/contraste/color/texto/fondo/gamma + tamaño",
    f_warp: "Curva por GPU · dial 0→1.5 · por panel",
    f_scan: "Viñeta · fósforo · tracking · vibración",
    f_crawl: "Perspectiva tipo Star Wars que se aleja (ángulo · profundidad)",
    f_gamba: "Una tragaperras gira mientras un agente piensa",
    f_detect: "Detectado · salta mensajes · timbre al terminar",
    f_focus: "Refleja un panel en grande sobre un desenfoque esmerilado",
    f_restore: "Caída / cierre → retoma el chat exacto",
    f_mcp: "Observación solo lectura + push · stdio, nunca TCP",
    scope_pane: "ESTE PANEL",
    scope_outer: "EXTERIOR",
    follow_outer: "seguir exterior",
    d_display: "GAUGES",
    g_text_size: "tamaño de texto",
    g_brightness: "brillo",
    g_contrast: "contraste",
    g_colour: "color",
    g_text: "texto",
    g_background: "fondo",
    g_gamma: "gamma",
    g_menu_bar: "barra de menú",
    g_warp: "curvatura",
    d_reset: "restablecer",
    d_roll: "barrido",
    d_roll_spd: "vel. barrido",
    d_roll_size: "tam. barrido",
    d_roll_reset: "barrido → por tema",
    d_crawl_hdr: "DESPLAZAMIENTO DE TEXTO",
    d_crawl_on: "despl. activado",
    d_crawl_off: "despl. desactivado",
    d_angle: "ángulo",
    d_depth: "profundidad",
    k_alt_arrows: "Alt + flechas",
    k_drag_subtab: "arrastrar subpestaña",
    k_rclick_tab: "clic derecho en pestaña",
    k_rclick: "clic derecho",
    k_dbl_click: "doble / triple clic",
    k_shift_ctrl_click: "Mayús- o Ctrl-clic",
    k_scroll_wheel: "rueda del ratón",
    k_theme_icon: "icono de tema (arriba dcha.)",
    k_display_tray: "GAUGES tray",
    k_text_size_key: "A──A · Ctrl+rueda",
    k_warp_dial: "dial de curvatura",
    k_pane_header: "(cabecera del panel)",
    k_focus_inherit_key: "LENTE · Heredar tema",
    k_wheel_key: "rueda / Mayús+rueda",
    k_input_colour: "color de tu entrada",
    k_bell_finish: "campana al terminar",
    k_mother_bar: "(barra madre)",
    kf_tiling: "árbol de mosaico",
    kf_groups: "grupos de pestañas",
    kf_drag: "arrastrar subpestaña",
    kf_rename: "renombrado avanzado",
    kf_popout: "ventana emergente",
    kf_themes: "4 temas + personalizado",
    kf_perpane: "aspecto por panel",
    kf_wheel: "rueda de color",
    kf_grade: "ajuste de monitor",
    kf_warp: "curvatura de barril",
    kf_scan: "líneas de barrido · brillo",
    kf_crawl: "desplazamiento de texto",
    kf_restore: "restaurar sesión",
    kf_mcp: "servidor MCP",
    t_theme: "DESIGN",
    t_wheel: "RUEDA · arrastra un pip · ◉ semilla T texto C compl.",
    t_program: "COLOR DEL PROGRAMA",
    t_syntax: "SINTAXIS",
    cm_ansi: "ansi",
    cm_mono: "mono",
    cm_theme: "tema",
    sc_off: "no",
    sc_code: "código",
    sc_agentic: "agéntico",
    sc_logs: "registros",
    sc_mark: "markdown",
    m_control: "CONTROL",
    m_read_only: "SOLO LECTURA",
    m_read_write: "LECTURA + ESCRITURA",
    m_server_on: "servidor activado",
    m_server_off: "servidor desactivado",
    m_expose: "exponer:",
    exp_agents: "solo agentes",
    exp_all: "todos los paneles",
    m_events_on: "transmitir eventos de herramientas",
    m_events_off: "eventos desactivados",
    m_writes_on: "escritura activada · los agentes pueden reestilizar",
    m_writes_off: "escritura desactivada · solo lectura",
    m_theme_on: "tema · activado",
    m_theme_off: "tema · desactivado",
    m_no_panes: "sin paneles",
    m_exposed: "panel(es) expuesto(s)",
    m_watches: "observa paneles de agentes · nunca escribe en un PTY",
    m_transport: "transporte del servidor: próxima entrega",
    thm_quiet: "tranquilo",
    thm_field: "campo",
    thm_tactical: "táctico",
    thm_hacker: "hacker",
    thm_gamba: "tragaperras",
    thm_custom: "personalizado",
    focus_name: "LENTE",
    gamba_name: "TRAGAPERRAS",
    ch_split: "dividir",
    ch_sub_terminal: "SUBTERMINAL",
    st_tab: "pestaña",
    st_tabs: "pestañas",
    st_pane: "panel",
    st_panes: "paneles",
    ch_ready: "LISTO",
    ph_live: "en vivo",
    ph_exited: "salió",
    ph_done: "listo",
    ph_shell: "CONSOLA",
    ph_remote: "REMOTO",
    dead_agents: "AGENTES MUERTOS",
    resurrect: "RESUCITAR",
    recoverable: "recuperables",
    dead: "muertos",
    no_recoverable: "No hay agentes recuperables \u{2014} cada sesión guardada está activa o ya desaparecida.",
    dead_hint: "haz clic en una fila para resucitarla \u{2014} o \u{2b07} .cdx para extraer su contexto a un paquete portátil",
};

/// Deutsch.
pub const DE: Strings = Strings {
    brand: "TERMINALE WONNE",
    help: "HILFE",
    shortcuts: "TASTENKÜRZEL",
    features: "FUNKTIONEN",
    demo_btn: "Eine Demo dieses Layouts starten",
    demo_sub: "öffnet ein neues Fenster, das genau dieses Layout klont, jedes Panel mit Blindtext gefüllt — sicher zum Teilen des Bildschirms",
    help_footer: "Esc oder Klick außerhalb zum Schließen · Themes sind live editierbares TOML zur Laufzeit",
    s_tabs: "TABS & PANELS",
    s_edit: "BEARBEITEN & ZWISCHENABLAGE",
    s_links: "LINKS",
    s_scroll: "VERLAUF",
    s_look: "ERSCHEINUNGSBILD",
    s_agents: "AGENTEN · claude / codex",
    s_window: "FENSTER",
    s_feat: "PANELS · TABS · FENSTER",
    s_theming: "THEMES",
    s_crt: "CRT · BEWEGUNG",
    s_amcp: "AGENTEN · MCP",
    new_tab: "Neuer Tab",
    switch_tabs: "Tabs wechseln",
    move_tab: "Tab verschieben (in / zwischen Gruppen)",
    split: "Teilen ↔ / ↕",
    move_focus: "Fokus zwischen Panels bewegen",
    drag_subtab: "Verschieben / teilen · herausziehen = neues Fenster",
    rclick_tab: "Umbenennen · Farbe · Gruppe",
    rclick: "Kopieren · Einfügen · Link öffnen · Leeren",
    copy_paste: "Kopieren / Einfügen",
    cut: "Auswahl ausschneiden (löscht in der Eingabezeile)",
    find: "In diesem Panel suchen (unscharf) — ↵ springt hin",
    find_all: "In ALLEN Panels suchen (unscharf)",
    select_wl: "Wort / Zeile auswählen",
    newline: "Zeilenumbruch (mehrzeilig in claude/codex)",
    open_link: "Eine URL oder einen Dateipfad öffnen",
    scroll_hist: "Verlauf scrollen",
    clear_scroll: "Verlauf leeren (nicht Ctrl+L)",
    themes_wheel: "DESIGN — Themes & Farbrad",
    display_tray: "GAUGES — Monitor-Abstimmung · Textgröße · Text-Crawl",
    text_size: "Textgröße",
    warp: "Das Glas wölben (0 = flach → Fischglas)",
    jump_msg: "Zur vorherigen / nächsten Nachricht springen",
    nav_msg: "Dasselbe — durch eigene Nachrichten navigieren",
    focus: "LUPE — dieses Panel groß spiegeln",
    focus_inherit: "Der Leser wölbt und glänzt wie sein Panel",
    pan_focus: "Eine gezoomte LUPE-Ansicht nach unten / seitlich schwenken",
    input_colour: "Deine Beiträge stechen hervor (👤-Rad-Pip)",
    bell: "Panel zeigt ● fertig + einen Ton pro Agent",
    mcp: "MCP — schreibgeschützte Agenten-Beobachtung",
    new_window: "Neues Fenster (schneller Notizblock)",
    f_tiling: "Teilungen betreffen nur das fokussierte Panel",
    f_groups: "Farbband · Griff-Chip · Einklapp-Pille",
    f_drag: "Teilen, verschieben oder als neues Fenster abtrennen",
    f_rename: "Cursor, Auswahl, Wortnavigation in Tab-Namen",
    f_popout: "Schnelles Fenster · einzel-instanz-bewusst",
    f_themes: "Live editierbares TOML, ~300ms Hot-Reload",
    f_perpane: "Theme & Abstimmung werden vererbt · „äußerem folgen“",
    f_wheel: "3 Marker — Saat · Text · Komplement",
    f_grade: "Helligkeit/Kontrast/Farbe/Text/Hintergrund/Gamma + Größe",
    f_warp: "GPU-Wölbung · Regler 0→1.5 · pro Panel",
    f_scan: "Vignette · Phosphor · Tracking · Zittern",
    f_crawl: "Star-Wars-Perspektive, die zurückweicht (Winkel · Tiefe)",
    f_gamba: "Ein Spielautomat dreht, während ein Agent nachdenkt",
    f_detect: "Erkannt · Nachrichten überspringen · Fertig-Glocke",
    f_focus: "Ein Panel groß über einer Mattglas-Unschärfe spiegeln",
    f_restore: "Absturz / Beenden → genau den Chat wiederaufnehmen",
    f_mcp: "Schreibgeschützte Beobachtung + Push · stdio, nie TCP",
    scope_pane: "DIESES PANEL",
    scope_outer: "ÄUSSERES",
    follow_outer: "äußerem folgen",
    d_display: "GAUGES",
    g_text_size: "Textgröße",
    g_brightness: "Helligkeit",
    g_contrast: "Kontrast",
    g_colour: "Farbe",
    g_text: "Text",
    g_background: "Hintergrund",
    g_gamma: "Gamma",
    g_menu_bar: "Menüleiste",
    g_warp: "Wölbung",
    d_reset: "zurücksetzen",
    d_roll: "Lauf",
    d_roll_spd: "Lauftempo",
    d_roll_size: "Laufgröße",
    d_roll_reset: "Lauf → pro Theme",
    d_crawl_hdr: "TEXT-CRAWL",
    d_crawl_on: "Crawl an",
    d_crawl_off: "Crawl aus",
    d_angle: "Winkel",
    d_depth: "Tiefe",
    k_alt_arrows: "Alt + Pfeile",
    k_drag_subtab: "Untertab ziehen",
    k_rclick_tab: "Rechtsklick auf Tab",
    k_rclick: "Rechtsklick",
    k_dbl_click: "Doppel- / Dreifachklick",
    k_shift_ctrl_click: "Umschalt- oder Strg-Klick",
    k_scroll_wheel: "Mausrad",
    k_theme_icon: "Theme-Symbol (oben rechts)",
    k_display_tray: "GAUGES tray",
    k_text_size_key: "A──A · Strg+Rad",
    k_warp_dial: "Wölbungsregler",
    k_pane_header: "(Panel-Kopf)",
    k_focus_inherit_key: "LUPE · Theme erben",
    k_wheel_key: "Rad / Umschalt+Rad",
    k_input_colour: "Farbe deiner Eingabe",
    k_bell_finish: "Glocke bei Fertig",
    k_mother_bar: "(Mutterleiste)",
    kf_tiling: "Kachelbaum",
    kf_groups: "Tab-Gruppen",
    kf_drag: "Untertab ziehen",
    kf_rename: "Reiches Umbenennen",
    kf_popout: "Pop-out-Notizfenster",
    kf_themes: "4 Themes + eigenes",
    kf_perpane: "Look pro Panel",
    kf_wheel: "Farbrad",
    kf_grade: "Monitor-Abstimmung",
    kf_warp: "Tonnenwölbung",
    kf_scan: "Scanlinien · Glühen",
    kf_crawl: "Text-Crawl",
    kf_restore: "Sitzung wiederherstellen",
    kf_mcp: "MCP-Server",
    t_theme: "DESIGN",
    t_wheel: "RAD · einen Pip herausziehen · ◉ Saat T Text C Kompl.",
    t_program: "PROGRAMMFARBE",
    t_syntax: "SYNTAX",
    cm_ansi: "ansi",
    cm_mono: "mono",
    cm_theme: "Theme",
    sc_off: "aus",
    sc_code: "Code",
    sc_agentic: "agentisch",
    sc_logs: "Logs",
    sc_mark: "Markdown",
    m_control: "STEUERUNG",
    m_read_only: "NUR LESEN",
    m_read_write: "LESEN + SCHREIBEN",
    m_server_on: "Server aktiviert",
    m_server_off: "Server deaktiviert",
    m_expose: "freigeben:",
    exp_agents: "nur Agenten",
    exp_all: "alle Panels",
    m_events_on: "Tool-Aufruf-Ereignisse streamen",
    m_events_off: "Ereignisse aus",
    m_writes_on: "Schreiben an · Agenten können umgestalten",
    m_writes_off: "Schreiben aus · nur Lesen",
    m_theme_on: "Theme · an",
    m_theme_off: "Theme · aus",
    m_no_panes: "keine Panels",
    m_exposed: "Panel(s) freigegeben",
    m_watches: "beobachtet Agenten-Panels · schreibt nie in ein PTY",
    m_transport: "Server-Transport: nächste Stufe",
    thm_quiet: "ruhig",
    thm_field: "Feld",
    thm_tactical: "taktisch",
    thm_hacker: "Hacker",
    thm_gamba: "Slots",
    thm_custom: "eigenes",
    focus_name: "LUPE",
    gamba_name: "SLOTS",
    ch_split: "teilen",
    ch_sub_terminal: "SUB-TERMINAL",
    st_tab: "Tab",
    st_tabs: "Tabs",
    st_pane: "Panel",
    st_panes: "Panels",
    ch_ready: "BEREIT",
    ph_live: "live",
    ph_exited: "beendet",
    ph_done: "fertig",
    ph_shell: "KONSOLE",
    ph_remote: "ENTFERNT",
    dead_agents: "TOTE AGENTEN",
    resurrect: "WIEDERBELEBEN",
    recoverable: "wiederherstellbar",
    dead: "tot",
    no_recoverable: "Keine wiederherstellbaren Agenten \u{2014} jede gespeicherte Sitzung ist entweder aktiv oder bereits weg.",
    dead_hint: "Klicke auf eine Zeile, um sie wiederzubeleben \u{2014} oder \u{2b07} .cdx, um ihren Kontext in ein portables Paket zu sichern",
};

/// 中文 (简体).
pub const ZH: Strings = Strings {
    brand: "终端之悦",
    help: "帮助",
    shortcuts: "快捷键",
    features: "功能",
    demo_btn: "启动此布局的演示",
    demo_sub: "打开一个克隆当前布局的新窗口，每个面板都填充示例文本——可安全用于共享屏幕",
    help_footer: "按 Esc 或点击外部关闭 · 运行时主题是可实时编辑的 TOML",
    s_tabs: "标签页与面板",
    s_edit: "编辑与剪贴板",
    s_links: "链接",
    s_scroll: "回滚",
    s_look: "外观",
    s_agents: "智能体 · claude / codex",
    s_window: "窗口",
    s_feat: "面板 · 标签页 · 窗口",
    s_theming: "主题",
    s_crt: "CRT · 动效",
    s_amcp: "智能体 · MCP",
    new_tab: "新建标签页",
    switch_tabs: "切换标签页",
    move_tab: "移动标签页（组内 / 跨组）",
    split: "拆分 ↔ / ↕",
    move_focus: "在面板间移动焦点",
    drag_subtab: "移动 / 拆分 · 拖出 = 新窗口",
    rclick_tab: "重命名 · 颜色 · 分组",
    rclick: "复制 · 粘贴 · 打开链接 · 清屏",
    copy_paste: "复制 / 粘贴",
    cut: "剪切所选（在输入行上会删除）",
    find: "在此面板中查找（模糊）——↵ 跳转",
    find_all: "在所有面板中查找（模糊）",
    select_wl: "选择单词 / 整行",
    newline: "换行（在 claude/codex 中可多行）",
    open_link: "打开网址或文件路径",
    scroll_hist: "滚动历史",
    clear_scroll: "清除回滚（非 Ctrl+L）",
    themes_wheel: "DESIGN — 主题与色环",
    display_tray: "GAUGES — 显示器调校 · 文字大小 · 文字滚屏",
    text_size: "文字大小",
    warp: "弯曲屏幕（0 = 平面 → 鱼缸）",
    jump_msg: "跳到你的上一条 / 下一条消息",
    nav_msg: "同上——浏览你自己的消息",
    focus: "放大镜——放大镜像此面板",
    focus_inherit: "阅读器像其面板一样弯曲并泛光",
    pan_focus: "平移放大的 放大镜 阅读：向下 / 左右",
    input_colour: "你的发言更突出（👤 色环标记）",
    bell: "面板显示 ● 完成 + 每个智能体的提示音",
    mcp: "MCP——只读的智能体观察面",
    new_window: "新窗口（快速草稿）",
    f_tiling: "拆分只切分当前聚焦的面板",
    f_groups: "色带 · 手柄标签 · 折叠胶囊",
    f_drag: "拆分、移动或撕出为新窗口",
    f_rename: "标签名支持光标、选择与按词导航",
    f_popout: "快速窗口 · 感知单实例",
    f_themes: "可实时编辑的 TOML，约 300 毫秒热重载",
    f_perpane: "主题与调校可继承 · “跟随外层”",
    f_wheel: "3 个标记——种子 · 文字 · 补色",
    f_grade: "亮度/对比度/颜色/文字/背景/伽马 + 大小",
    f_warp: "GPU 曲面 · 0→1.5 旋钮 · 逐面板",
    f_scan: "暗角 · 荧光 · 行扫 · 抖动",
    f_crawl: "《星球大战》式向远处后退的透视（角度 · 深度）",
    f_gamba: "智能体思考时老虎机转动",
    f_detect: "已检测 · 跳转消息 · 完成提示音",
    f_focus: "在磨砂模糊上放大镜像一个面板",
    f_restore: "崩溃 / 退出 → 恢复到完全相同的会话",
    f_mcp: "只读观察 + 推送 · stdio，绝不用 TCP",
    scope_pane: "本面板",
    scope_outer: "外层",
    follow_outer: "跟随外层",
    d_display: "GAUGES",
    g_text_size: "文字大小",
    g_brightness: "亮度",
    g_contrast: "对比度",
    g_colour: "颜色",
    g_text: "文字",
    g_background: "背景",
    g_gamma: "伽马",
    g_menu_bar: "菜单栏",
    g_warp: "弯曲",
    d_reset: "重置",
    d_roll: "滚动条",
    d_roll_spd: "滚动速度",
    d_roll_size: "滚动大小",
    d_roll_reset: "滚动条 → 按主题",
    d_crawl_hdr: "文字滚屏",
    d_crawl_on: "滚屏开",
    d_crawl_off: "滚屏关",
    d_angle: "角度",
    d_depth: "深度",
    k_alt_arrows: "Alt + 方向键",
    k_drag_subtab: "拖动子标签",
    k_rclick_tab: "右键点击标签",
    k_rclick: "右键点击",
    k_dbl_click: "双击 / 三击",
    k_shift_ctrl_click: "Shift 或 Ctrl 点击",
    k_scroll_wheel: "滚轮",
    k_theme_icon: "主题图标（右上角）",
    k_display_tray: "GAUGES tray",
    k_text_size_key: "A──A · Ctrl+滚轮",
    k_warp_dial: "弯曲旋钮",
    k_pane_header: "（面板标题栏）",
    k_focus_inherit_key: "放大镜 · 继承主题",
    k_wheel_key: "滚轮 / Shift+滚轮",
    k_input_colour: "你的输入颜色",
    k_bell_finish: "完成时响铃",
    k_mother_bar: "（母栏）",
    kf_tiling: "平铺树",
    kf_groups: "标签分组",
    kf_drag: "拖动子标签",
    kf_rename: "丰富重命名",
    kf_popout: "弹出草稿",
    kf_themes: "4 个主题 + 自定义",
    kf_perpane: "逐面板外观",
    kf_wheel: "色环",
    kf_grade: "显示器调校",
    kf_warp: "桶形弯曲",
    kf_scan: "扫描线 · 辉光",
    kf_crawl: "文字滚屏",
    kf_restore: "会话恢复",
    kf_mcp: "MCP 服务器",
    t_theme: "DESIGN",
    t_wheel: "色环 · 拖出一个圆点 · ◉ 种子 T 文字 C 补色",
    t_program: "程序颜色",
    t_syntax: "语法",
    cm_ansi: "ansi",
    cm_mono: "单色",
    cm_theme: "主题",
    sc_off: "关",
    sc_code: "代码",
    sc_agentic: "智能体",
    sc_logs: "日志",
    sc_mark: "标记",
    m_control: "控制",
    m_read_only: "只读",
    m_read_write: "读 + 写",
    m_server_on: "服务器已启用",
    m_server_off: "服务器已禁用",
    m_expose: "暴露：",
    exp_agents: "仅智能体",
    exp_all: "所有面板",
    m_events_on: "推送工具调用事件",
    m_events_off: "事件关闭",
    m_writes_on: "写入开启 · 智能体可重设样式",
    m_writes_off: "写入关闭 · 只读",
    m_theme_on: "主题 · 开",
    m_theme_off: "主题 · 关",
    m_no_panes: "无面板",
    m_exposed: "个面板已暴露",
    m_watches: "观察智能体面板 · 绝不写入 PTY",
    m_transport: "实时服务器传输：下一步",
    thm_quiet: "安静",
    thm_field: "野战",
    thm_tactical: "战术",
    thm_hacker: "黑客",
    thm_gamba: "老虎机",
    thm_custom: "自定义",
    focus_name: "放大镜",
    gamba_name: "老虎机",
    ch_split: "拆分",
    ch_sub_terminal: "子终端",
    st_tab: "标签页",
    st_tabs: "标签页",
    st_pane: "面板",
    st_panes: "面板",
    ch_ready: "就绪",
    ph_live: "实时",
    ph_exited: "已退出",
    ph_done: "完成",
    ph_shell: "外壳",
    ph_remote: "远程",
    dead_agents: "已死代理",
    resurrect: "复活",
    recoverable: "可恢复",
    dead: "已死",
    no_recoverable: "没有可恢复的代理 \u{2014} 每个已保存的会话要么仍在运行，要么已经消失。",
    dead_hint: "点击某一行即可复活它 \u{2014} 或点击 \u{2b07} .cdx 将其上下文导出为可移植的包",
};

/// Français.
pub const FR: Strings = Strings {
    brand: "DÉLICE TERMINAL",
    help: "AIDE",
    shortcuts: "RACCOURCIS",
    features: "FONCTIONS",
    demo_btn: "Lancer une démo de cette disposition",
    demo_sub: "ouvre une nouvelle fenêtre clonant cette disposition, chaque volet rempli de texte fictif — sûr pour le partage d'écran",
    help_footer: "Échap ou clic à l'extérieur pour fermer · les thèmes sont du TOML éditable en direct",
    s_tabs: "ONGLETS ET VOLETS",
    s_edit: "ÉDITION ET PRESSE-PAPIERS",
    s_links: "LIENS",
    s_scroll: "HISTORIQUE",
    s_look: "APPARENCE",
    s_agents: "AGENTS · claude / codex",
    s_window: "FENÊTRE",
    s_feat: "VOLETS · ONGLETS · FENÊTRE",
    s_theming: "THÈMES",
    s_crt: "CRT · MOUVEMENT",
    s_amcp: "AGENTS · MCP",
    new_tab: "Nouvel onglet",
    switch_tabs: "Changer d'onglet",
    move_tab: "Déplacer l'onglet (dans / entre les groupes)",
    split: "Diviser ↔ / ↕",
    move_focus: "Déplacer le focus entre les volets",
    drag_subtab: "Déplacer / diviser · glisser dehors = nouvelle fenêtre",
    rclick_tab: "Renommer · couleur · groupe",
    rclick: "Copier · Coller · Ouvrir le lien · Effacer",
    copy_paste: "Copier / Coller",
    cut: "Couper la sélection (supprime sur la ligne de saisie)",
    find: "Rechercher dans ce volet (flou) — ↵ y saute",
    find_all: "Rechercher dans TOUS les volets (flou)",
    select_wl: "Sélectionner mot / ligne",
    newline: "Nouvelle ligne (multiligne dans claude/codex)",
    open_link: "Ouvrir une URL ou un chemin de fichier",
    scroll_hist: "Faire défiler l'historique",
    clear_scroll: "Effacer l'historique (pas Ctrl+L)",
    themes_wheel: "DESIGN — Thèmes et roue chromatique",
    display_tray: "GAUGES — Réglage écran · taille du texte · défilement",
    text_size: "Taille du texte",
    warp: "Courber le verre (0 = plat → bocal)",
    jump_msg: "Sauter à votre message précédent / suivant",
    nav_msg: "Pareil — parcourir vos propres messages",
    focus: "LOUPE — refléter ce volet en grand",
    focus_inherit: "Le lecteur se courbe et brille comme son volet",
    pan_focus: "Faire glisser une lecture LOUPE zoomée bas / côtés",
    input_colour: "Vos tours ressortent (pastille 👤 de la roue)",
    bell: "Le volet affiche ● terminé + un son par agent",
    mcp: "MCP — surface d'observation des agents, lecture seule",
    new_window: "Nouvelle fenêtre (brouillon rapide)",
    f_tiling: "Les divisions ne touchent que le volet ciblé",
    f_groups: "Bande de couleur · puce de poignée · pastille de repli",
    f_drag: "Diviser, déplacer ou détacher une nouvelle fenêtre",
    f_rename: "Curseur, sélection, navigation par mot dans les noms",
    f_popout: "Fenêtre rapide · consciente de l'instance unique",
    f_themes: "TOML éditable en direct, rechargement ~300ms",
    f_perpane: "Thème et réglage hérités · « suivre l'extérieur »",
    f_wheel: "3 marqueurs — graine · texte · complément",
    f_grade: "Lumin./contraste/couleur/texte/fond/gamma + taille",
    f_warp: "Courbe GPU · molette 0→1.5 · par volet",
    f_scan: "Vignette · phosphore · tracking · tremblement",
    f_crawl: "Perspective à la Star Wars qui recule (angle · profondeur)",
    f_gamba: "Une machine à sous tourne pendant qu'un agent réfléchit",
    f_detect: "Détecté · sauter les messages · cloche de fin",
    f_focus: "Refléter un volet en grand sur un flou dépoli",
    f_restore: "Plantage / fermeture → reprendre le chat exact",
    f_mcp: "Observation lecture seule + push · stdio, jamais TCP",
    scope_pane: "CE VOLET",
    scope_outer: "EXTÉRIEUR",
    follow_outer: "suivre l'extérieur",
    d_display: "GAUGES",
    g_text_size: "taille du texte",
    g_brightness: "luminosité",
    g_contrast: "contraste",
    g_colour: "couleur",
    g_text: "texte",
    g_background: "fond",
    g_gamma: "gamma",
    g_menu_bar: "barre de menu",
    g_warp: "courbure",
    d_reset: "réinitialiser",
    d_roll: "roulis",
    d_roll_spd: "vit. roulis",
    d_roll_size: "taille roulis",
    d_roll_reset: "roulis → par thème",
    d_crawl_hdr: "DÉFILEMENT TEXTE",
    d_crawl_on: "défil. activé",
    d_crawl_off: "défil. désactivé",
    d_angle: "angle",
    d_depth: "profondeur",
    k_alt_arrows: "Alt + flèches",
    k_drag_subtab: "glisser un sous-onglet",
    k_rclick_tab: "clic droit sur un onglet",
    k_rclick: "clic droit",
    k_dbl_click: "double / triple clic",
    k_shift_ctrl_click: "Maj- ou Ctrl-clic",
    k_scroll_wheel: "molette",
    k_theme_icon: "icône de thème (en haut à dr.)",
    k_display_tray: "GAUGES tray",
    k_text_size_key: "A──A · Ctrl+molette",
    k_warp_dial: "molette de courbure",
    k_pane_header: "(en-tête du volet)",
    k_focus_inherit_key: "LOUPE · Hériter le thème",
    k_wheel_key: "molette / Maj+molette",
    k_input_colour: "couleur de votre saisie",
    k_bell_finish: "cloche à la fin",
    k_mother_bar: "(barre mère)",
    kf_tiling: "arbre de pavage",
    kf_groups: "groupes d'onglets",
    kf_drag: "glisser un sous-onglet",
    kf_rename: "renommage enrichi",
    kf_popout: "fenêtre détachée",
    kf_themes: "4 thèmes + perso",
    kf_perpane: "apparence par volet",
    kf_wheel: "roue chromatique",
    kf_grade: "réglage écran",
    kf_warp: "courbure en tonneau",
    kf_scan: "lignes de balayage · halo",
    kf_crawl: "défilement de texte",
    kf_restore: "restaurer la session",
    kf_mcp: "serveur MCP",
    t_theme: "DESIGN",
    t_wheel: "ROUE · sortez un pip · ◉ graine T texte C compl.",
    t_program: "COULEUR DU PROGRAMME",
    t_syntax: "SYNTAXE",
    cm_ansi: "ansi",
    cm_mono: "mono",
    cm_theme: "thème",
    sc_off: "non",
    sc_code: "code",
    sc_agentic: "agentique",
    sc_logs: "journaux",
    sc_mark: "markdown",
    m_control: "CONTRÔLE",
    m_read_only: "LECTURE SEULE",
    m_read_write: "LECTURE + ÉCRITURE",
    m_server_on: "serveur activé",
    m_server_off: "serveur désactivé",
    m_expose: "exposer :",
    exp_agents: "agents seulement",
    exp_all: "tous les volets",
    m_events_on: "diffuser les événements d'outils",
    m_events_off: "événements désactivés",
    m_writes_on: "écriture activée · les agents peuvent restyler",
    m_writes_off: "écriture désactivée · lecture seule",
    m_theme_on: "thème · activé",
    m_theme_off: "thème · désactivé",
    m_no_panes: "aucun volet",
    m_exposed: "volet(s) exposé(s)",
    m_watches: "observe les volets d'agents · n'écrit jamais dans un PTY",
    m_transport: "transport du serveur : prochaine étape",
    thm_quiet: "calme",
    thm_field: "champ",
    thm_tactical: "tactique",
    thm_hacker: "hacker",
    thm_gamba: "casino",
    thm_custom: "perso",
    focus_name: "LOUPE",
    gamba_name: "CASINO",
    ch_split: "diviser",
    ch_sub_terminal: "SOUS-TERMINAL",
    st_tab: "onglet",
    st_tabs: "onglets",
    st_pane: "volet",
    st_panes: "volets",
    ch_ready: "PRÊT",
    ph_live: "en direct",
    ph_exited: "quitté",
    ph_done: "terminé",
    ph_shell: "CONSOLE",
    ph_remote: "DISTANT",
    dead_agents: "AGENTS MORTS",
    resurrect: "RESSUSCITER",
    recoverable: "récupérables",
    dead: "morts",
    no_recoverable: "Aucun agent récupérable \u{2014} chaque session enregistrée est soit active, soit déjà disparue.",
    dead_hint: "cliquez sur une ligne pour la ressusciter \u{2014} ou \u{2b07} .cdx pour exporter son contexte dans un paquet portable",
};

/// Русский.
pub const RU: Strings = Strings {
    brand: "ТЕРМИНАЛЬНОЕ БЛАЖЕНСТВО",
    help: "СПРАВКА",
    shortcuts: "СОЧЕТАНИЯ КЛАВИШ",
    features: "ВОЗМОЖНОСТИ",
    demo_btn: "Запустить демо этой раскладки",
    demo_sub: "откроет новое окно, клонирующее эту раскладку, каждая панель заполнена текстом-рыбой — безопасно для демонстрации экрана",
    help_footer: "Esc или клик снаружи чтобы закрыть · темы — это TOML, редактируемый на ходу",
    s_tabs: "ВКЛАДКИ И ПАНЕЛИ",
    s_edit: "РЕДАКТИРОВАНИЕ И БУФЕР",
    s_links: "ССЫЛКИ",
    s_scroll: "ПРОКРУТКА",
    s_look: "ВНЕШНИЙ ВИД",
    s_agents: "АГЕНТЫ · claude / codex",
    s_window: "ОКНО",
    s_feat: "ПАНЕЛИ · ВКЛАДКИ · ОКНО",
    s_theming: "ТЕМЫ",
    s_crt: "CRT · ДВИЖЕНИЕ",
    s_amcp: "АГЕНТЫ · MCP",
    new_tab: "Новая вкладка",
    switch_tabs: "Переключить вкладки",
    move_tab: "Переместить вкладку (внутри / между группами)",
    split: "Разделить ↔ / ↕",
    move_focus: "Переместить фокус между панелями",
    drag_subtab: "Переместить / разделить · вытащить = новое окно",
    rclick_tab: "Переименовать · цвет · группа",
    rclick: "Копировать · Вставить · Открыть ссылку · Очистить",
    copy_paste: "Копировать / Вставить",
    cut: "Вырезать выделение (удаляет в строке ввода)",
    find: "Найти в этой панели (нечётко) — ↵ переход",
    find_all: "Найти во ВСЕХ панелях (нечётко)",
    select_wl: "Выделить слово / строку",
    newline: "Новая строка (многострочно в claude/codex)",
    open_link: "Открыть URL или путь к файлу",
    scroll_hist: "Прокрутить историю",
    clear_scroll: "Очистить прокрутку (не Ctrl+L)",
    themes_wheel: "DESIGN — Темы и цветовой круг",
    display_tray: "GAUGES — Настройка монитора · размер текста · бегущая строка",
    text_size: "Размер текста",
    warp: "Изогнуть стекло (0 = плоско → аквариум)",
    jump_msg: "Перейти к предыдущему / следующему сообщению",
    nav_msg: "То же — навигация по своим сообщениям",
    focus: "ЛУПА — отразить эту панель крупно",
    focus_inherit: "Читатель изгибается и бликует как его панель",
    pan_focus: "Панорама увеличенного ЛУПА вниз / в стороны",
    input_colour: "Ваши реплики выделяются (метка 👤 круга)",
    bell: "Панель показывает ● готово + звук на агента",
    mcp: "MCP — поверхность наблюдения за агентами, только чтение",
    new_window: "Новое окно (быстрый черновик)",
    f_tiling: "Разделения затрагивают только активную панель",
    f_groups: "Цветная полоса · чип-ручка · пилюля сворачивания",
    f_drag: "Разделить, переместить или отделить новое окно",
    f_rename: "Курсор, выделение, навигация по словам в именах",
    f_popout: "Быстрое окно · учитывает единственный экземпляр",
    f_themes: "Редактируемый на ходу TOML, перезагрузка ~300мс",
    f_perpane: "Тема и настройка наследуются · «следовать внешнему»",
    f_wheel: "3 маркера — зерно · текст · дополнение",
    f_grade: "Яркость/контраст/цвет/текст/фон/гамма + размер",
    f_warp: "Изгиб на GPU · регулятор 0→1.5 · по панели",
    f_scan: "Виньетка · люминофор · трекинг · дрожание",
    f_crawl: "Перспектива в стиле Звёздных войн, уходящая вдаль (угол · глубина)",
    f_gamba: "Игровой автомат крутится, пока агент думает",
    f_detect: "Обнаружено · переход по сообщениям · звонок готовности",
    f_focus: "Отразить панель крупно поверх матового размытия",
    f_restore: "Сбой / выход → возобновить точно тот же чат",
    f_mcp: "Наблюдение только для чтения + push · stdio, никогда TCP",
    scope_pane: "ЭТА ПАНЕЛЬ",
    scope_outer: "ВНЕШНИЙ",
    follow_outer: "следовать внешнему",
    d_display: "GAUGES",
    g_text_size: "размер текста",
    g_brightness: "яркость",
    g_contrast: "контраст",
    g_colour: "цвет",
    g_text: "текст",
    g_background: "фон",
    g_gamma: "гамма",
    g_menu_bar: "панель меню",
    g_warp: "изгиб",
    d_reset: "сброс",
    d_roll: "бегущая",
    d_roll_spd: "скор. бега",
    d_roll_size: "разм. бега",
    d_roll_reset: "бегущая → по теме",
    d_crawl_hdr: "БЕГУЩИЙ ТЕКСТ",
    d_crawl_on: "бегущий вкл",
    d_crawl_off: "бегущий выкл",
    d_angle: "угол",
    d_depth: "глубина",
    k_alt_arrows: "Alt + стрелки",
    k_drag_subtab: "тащить подвкладку",
    k_rclick_tab: "правый клик по вкладке",
    k_rclick: "правый клик",
    k_dbl_click: "двойной / тройной клик",
    k_shift_ctrl_click: "Shift- или Ctrl-клик",
    k_scroll_wheel: "колесо мыши",
    k_theme_icon: "значок темы (вверху справа)",
    k_display_tray: "GAUGES tray",
    k_text_size_key: "A──A · Ctrl+колесо",
    k_warp_dial: "регулятор изгиба",
    k_pane_header: "(шапка панели)",
    k_focus_inherit_key: "ЛУПА · Наследовать тему",
    k_wheel_key: "колесо / Shift+колесо",
    k_input_colour: "цвет вашего ввода",
    k_bell_finish: "звонок при завершении",
    k_mother_bar: "(материнская панель)",
    kf_tiling: "дерево мозаики",
    kf_groups: "группы вкладок",
    kf_drag: "тащить подвкладку",
    kf_rename: "богатое переименование",
    kf_popout: "всплывающее окно",
    kf_themes: "4 темы + своя",
    kf_perpane: "вид по панели",
    kf_wheel: "цветовой круг",
    kf_grade: "настройка монитора",
    kf_warp: "бочкообразный изгиб",
    kf_scan: "строки развёртки · свечение",
    kf_crawl: "бегущий текст",
    kf_restore: "восстановить сессию",
    kf_mcp: "сервер MCP",
    t_theme: "DESIGN",
    t_wheel: "КРУГ · вытащите точку · ◉ зерно T текст C дополн.",
    t_program: "ЦВЕТ ПРОГРАММЫ",
    t_syntax: "СИНТАКСИС",
    cm_ansi: "ansi",
    cm_mono: "моно",
    cm_theme: "тема",
    sc_off: "выкл",
    sc_code: "код",
    sc_agentic: "агентный",
    sc_logs: "логи",
    sc_mark: "markdown",
    m_control: "УПРАВЛЕНИЕ",
    m_read_only: "ТОЛЬКО ЧТЕНИЕ",
    m_read_write: "ЧТЕНИЕ + ЗАПИСЬ",
    m_server_on: "сервер включён",
    m_server_off: "сервер выключен",
    m_expose: "показать:",
    exp_agents: "только агенты",
    exp_all: "все панели",
    m_events_on: "транслировать события инструментов",
    m_events_off: "события выкл",
    m_writes_on: "запись вкл · агенты могут менять стиль",
    m_writes_off: "запись выкл · только чтение",
    m_theme_on: "тема · вкл",
    m_theme_off: "тема · выкл",
    m_no_panes: "нет панелей",
    m_exposed: "панелей показано",
    m_watches: "наблюдает панели агентов · никогда не пишет в PTY",
    m_transport: "транспорт сервера: следующий этап",
    thm_quiet: "тихая",
    thm_field: "поле",
    thm_tactical: "тактика",
    thm_hacker: "хакер",
    thm_gamba: "слоты",
    thm_custom: "своя",
    focus_name: "ЛУПА",
    gamba_name: "СЛОТЫ",
    ch_split: "разделить",
    ch_sub_terminal: "СУБТЕРМИНАЛ",
    st_tab: "вкладка",
    st_tabs: "вкладки",
    st_pane: "панель",
    st_panes: "панели",
    ch_ready: "ГОТОВО",
    ph_live: "активна",
    ph_exited: "завершено",
    ph_done: "готово",
    ph_shell: "ОБОЛОЧКА",
    ph_remote: "УДАЛЁННЫЙ",
    dead_agents: "МЁРТВЫЕ АГЕНТЫ",
    resurrect: "ВОСКРЕСИТЬ",
    recoverable: "восстановимых",
    dead: "мёртвых",
    no_recoverable: "Нет восстановимых агентов \u{2014} каждая сохранённая сессия либо активна, либо уже исчезла.",
    dead_hint: "нажмите на строку, чтобы воскресить её \u{2014} или \u{2b07} .cdx, чтобы выгрузить её контекст в переносимый пакет",
};

/// 日本語.
pub const JA: Strings = Strings {
    brand: "端末の悦び",
    help: "ヘルプ",
    shortcuts: "ショートカット",
    features: "機能",
    demo_btn: "このレイアウトのデモを起動",
    demo_sub: "このレイアウトを複製した新しいウィンドウを開き、各ペインをダミーテキストで埋めます — 画面共有に安全",
    help_footer: "Esc または外側をクリックで閉じる · テーマは実行中に編集できる TOML です",
    s_tabs: "タブとペイン",
    s_edit: "編集とクリップボード",
    s_links: "リンク",
    s_scroll: "スクロールバック",
    s_look: "外観",
    s_agents: "エージェント · claude / codex",
    s_window: "ウィンドウ",
    s_feat: "ペイン · タブ · ウィンドウ",
    s_theming: "テーマ",
    s_crt: "CRT · モーション",
    s_amcp: "エージェント · MCP",
    new_tab: "新しいタブ",
    switch_tabs: "タブを切り替え",
    move_tab: "タブを移動（グループ内 / グループ間）",
    split: "分割 ↔ / ↕",
    move_focus: "ペイン間でフォーカスを移動",
    drag_subtab: "移動 / 分割 · 外へドラッグ = 新しいウィンドウ",
    rclick_tab: "名前変更 · 色 · グループ",
    rclick: "コピー · 貼り付け · リンクを開く · クリア",
    copy_paste: "コピー / 貼り付け",
    cut: "選択を切り取り（入力行では削除）",
    find: "このペイン内を検索（あいまい）— ↵ で移動",
    find_all: "すべてのペインを検索（あいまい）",
    select_wl: "単語 / 行を選択",
    newline: "改行（claude/codex では複数行）",
    open_link: "URL またはファイルパスを開く",
    scroll_hist: "履歴をスクロール",
    clear_scroll: "スクロールバックをクリア（Ctrl+L ではない）",
    themes_wheel: "DESIGN — テーマとカラーホイール",
    display_tray: "GAUGES — モニター調整 · 文字サイズ · テキストクロール",
    text_size: "文字サイズ",
    warp: "画面を湾曲（0 = 平面 → 金魚鉢）",
    jump_msg: "前 / 次の自分のメッセージへ移動",
    nav_msg: "同上 — 自分のメッセージを移動",
    focus: "ルーペ — このペインを大きくミラー",
    focus_inherit: "リーダーがペインのように湾曲して光る",
    pan_focus: "拡大した ルーペ 表示を下 / 左右にパン",
    input_colour: "あなたの発言が目立つ（👤 ホイールのピップ）",
    bell: "ペインに ● 完了 + エージェントごとの音",
    mcp: "MCP — 読み取り専用のエージェント監視面",
    new_window: "新しいウィンドウ（クイックスクラッチ）",
    f_tiling: "分割はフォーカス中のペインのみを区切る",
    f_groups: "カラーバンド · ハンドルチップ · 折りたたみピル",
    f_drag: "分割、移動、または新しいウィンドウに切り離す",
    f_rename: "タブ名でカーソル・選択・単語移動",
    f_popout: "クイックウィンドウ · 単一インスタンス対応",
    f_themes: "実行中に編集できる TOML、約300ミリ秒でリロード",
    f_perpane: "テーマと調整を継承 ·「外側に従う」",
    f_wheel: "3つのマーカー — シード · テキスト · 補色",
    f_grade: "明るさ/コントラスト/色/文字/背景/ガンマ + サイズ",
    f_warp: "GPU 湾曲 · 0→1.5 ダイヤル · ペインごと",
    f_scan: "ビネット · 蛍光体 · トラッキング · 揺れ",
    f_crawl: "スター・ウォーズ風に遠ざかる遠近法（角度 · 深さ）",
    f_gamba: "エージェントが考える間スロットが回る",
    f_detect: "検出 · メッセージ移動 · 完了ベル",
    f_focus: "すりガラスのぼかしの上にペインを大きくミラー",
    f_restore: "クラッシュ / 終了 → まったく同じチャットを再開",
    f_mcp: "読み取り専用監視 + プッシュ · stdio、TCP は使わない",
    scope_pane: "このペイン",
    scope_outer: "外側",
    follow_outer: "外側に従う",
    d_display: "GAUGES",
    g_text_size: "文字サイズ",
    g_brightness: "明るさ",
    g_contrast: "コントラスト",
    g_colour: "色",
    g_text: "文字",
    g_background: "背景",
    g_gamma: "ガンマ",
    g_menu_bar: "メニューバー",
    g_warp: "湾曲",
    d_reset: "リセット",
    d_roll: "ロール",
    d_roll_spd: "ロール速度",
    d_roll_size: "ロール幅",
    d_roll_reset: "ロール → テーマ別",
    d_crawl_hdr: "テキストクロール",
    d_crawl_on: "クロール オン",
    d_crawl_off: "クロール オフ",
    d_angle: "角度",
    d_depth: "深さ",
    k_alt_arrows: "Alt + 矢印キー",
    k_drag_subtab: "サブタブをドラッグ",
    k_rclick_tab: "タブを右クリック",
    k_rclick: "右クリック",
    k_dbl_click: "ダブル / トリプルクリック",
    k_shift_ctrl_click: "Shift または Ctrl クリック",
    k_scroll_wheel: "スクロールホイール",
    k_theme_icon: "テーマアイコン（右上）",
    k_display_tray: "GAUGES tray",
    k_text_size_key: "A──A · Ctrl+ホイール",
    k_warp_dial: "湾曲ダイヤル",
    k_pane_header: "（ペインヘッダー）",
    k_focus_inherit_key: "ルーペ · テーマを継承",
    k_wheel_key: "ホイール / Shift+ホイール",
    k_input_colour: "あなたの入力の色",
    k_bell_finish: "完了時にベル",
    k_mother_bar: "（マザーバー）",
    kf_tiling: "タイルツリー",
    kf_groups: "タブグループ",
    kf_drag: "サブタブをドラッグ",
    kf_rename: "リッチな名前変更",
    kf_popout: "ポップアウトスクラッチ",
    kf_themes: "4 テーマ + カスタム",
    kf_perpane: "ペインごとの外観",
    kf_wheel: "カラーホイール",
    kf_grade: "モニター調整",
    kf_warp: "樽型湾曲",
    kf_scan: "走査線 · グロー",
    kf_crawl: "テキストクロール",
    kf_restore: "セッション復元",
    kf_mcp: "MCP サーバー",
    t_theme: "DESIGN",
    t_wheel: "ホイール · ピップを引き出す · ◉ シード T 文字 C 補色",
    t_program: "プログラム色",
    t_syntax: "構文",
    cm_ansi: "ansi",
    cm_mono: "モノ",
    cm_theme: "テーマ",
    sc_off: "オフ",
    sc_code: "コード",
    sc_agentic: "エージェント",
    sc_logs: "ログ",
    sc_mark: "マーク",
    m_control: "コントロール",
    m_read_only: "読み取り専用",
    m_read_write: "読み取り + 書き込み",
    m_server_on: "サーバー有効",
    m_server_off: "サーバー無効",
    m_expose: "公開：",
    exp_agents: "エージェントのみ",
    exp_all: "すべてのペイン",
    m_events_on: "ツール呼び出しイベントを配信",
    m_events_off: "イベント オフ",
    m_writes_on: "書き込みオン · エージェントが再スタイル可",
    m_writes_off: "書き込みオフ · 読み取り専用",
    m_theme_on: "テーマ · オン",
    m_theme_off: "テーマ · オフ",
    m_no_panes: "ペインなし",
    m_exposed: "ペインを公開",
    m_watches: "エージェントペインを監視 · PTY には書き込まない",
    m_transport: "ライブサーバー転送：次の段階",
    thm_quiet: "静か",
    thm_field: "フィールド",
    thm_tactical: "戦術",
    thm_hacker: "ハッカー",
    thm_gamba: "スロット",
    thm_custom: "カスタム",
    focus_name: "ルーペ",
    gamba_name: "スロット",
    ch_split: "分割",
    ch_sub_terminal: "サブターミナル",
    st_tab: "タブ",
    st_tabs: "タブ",
    st_pane: "ペイン",
    st_panes: "ペイン",
    ch_ready: "準備完了",
    ph_live: "ライブ",
    ph_exited: "終了",
    ph_done: "完了",
    ph_shell: "シェル",
    ph_remote: "リモート",
    dead_agents: "停止エージェント",
    resurrect: "復活",
    recoverable: "復元可能",
    dead: "停止",
    no_recoverable: "復元可能なエージェントはありません \u{2014} 保存済みセッションはすべて稼働中か、すでに消失しています。",
    dead_hint: "行をクリックして復活させる \u{2014} または \u{2b07} .cdx でそのコンテキストを可搬パッケージに取り込む",
};

/// 한국어.
pub const KO: Strings = Strings {
    brand: "터미널의 기쁨",
    help: "도움말",
    shortcuts: "단축키",
    features: "기능",
    demo_btn: "이 레이아웃의 데모 실행",
    demo_sub: "이 레이아웃을 복제한 새 창을 열고 각 창을 예시 텍스트로 채웁니다 — 화면 공유에 안전",
    help_footer: "Esc 또는 바깥 클릭으로 닫기 · 테마는 실행 중 편집 가능한 TOML",
    s_tabs: "탭과 창",
    s_edit: "편집과 클립보드",
    s_links: "링크",
    s_scroll: "스크롤백",
    s_look: "모양",
    s_agents: "에이전트 · claude / codex",
    s_window: "창",
    s_feat: "창 · 탭 · 윈도우",
    s_theming: "테마",
    s_crt: "CRT · 모션",
    s_amcp: "에이전트 · MCP",
    new_tab: "새 탭",
    switch_tabs: "탭 전환",
    move_tab: "탭 이동 (그룹 내 / 그룹 간)",
    split: "분할 ↔ / ↕",
    move_focus: "창 사이로 포커스 이동",
    drag_subtab: "이동 / 분할 · 밖으로 끌기 = 새 창",
    rclick_tab: "이름 변경 · 색 · 그룹",
    rclick: "복사 · 붙여넣기 · 링크 열기 · 지우기",
    copy_paste: "복사 / 붙여넣기",
    cut: "선택 잘라내기 (입력 줄에서는 삭제)",
    find: "이 창에서 찾기 (퍼지) — ↵ 로 이동",
    find_all: "모든 창에서 찾기 (퍼지)",
    select_wl: "단어 / 줄 선택",
    newline: "줄바꿈 (claude/codex 에서 여러 줄)",
    open_link: "URL 또는 파일 경로 열기",
    scroll_hist: "기록 스크롤",
    clear_scroll: "스크롤백 지우기 (Ctrl+L 아님)",
    themes_wheel: "DESIGN — 테마와 색상환",
    display_tray: "GAUGES — 모니터 보정 · 글자 크기 · 텍스트 크롤",
    text_size: "글자 크기",
    warp: "화면 휘기 (0 = 평면 → 어항)",
    jump_msg: "이전 / 다음 내 메시지로 이동",
    nav_msg: "동일 — 내 메시지 탐색",
    focus: "돋보기 — 이 창을 크게 미러링",
    focus_inherit: "리더가 창처럼 휘고 빛남",
    pan_focus: "확대된 돋보기 보기를 아래 / 좌우로 이동",
    input_colour: "당신의 차례가 돋보임 (👤 휠 핍)",
    bell: "창에 ● 완료 + 에이전트별 소리 표시",
    mcp: "MCP — 읽기 전용 에이전트 관찰 면",
    new_window: "새 창 (빠른 스크래치)",
    f_tiling: "분할은 포커스된 창만 나눔",
    f_groups: "색 띠 · 핸들 칩 · 접기 알약",
    f_drag: "분할, 이동 또는 새 창으로 떼어내기",
    f_rename: "탭 이름에서 커서, 선택, 단어 이동",
    f_popout: "빠른 창 · 단일 인스턴스 인식",
    f_themes: "실행 중 편집 가능한 TOML, 약 300ms 핫 리로드",
    f_perpane: "테마와 보정 상속 · '외부 따르기'",
    f_wheel: "마커 3개 — 시드 · 텍스트 · 보색",
    f_grade: "밝기/대비/색/글자/배경/감마 + 크기",
    f_warp: "GPU 곡면 · 0→1.5 다이얼 · 창별",
    f_scan: "비네트 · 인광 · 트래킹 · 떨림",
    f_crawl: "스타워즈식 멀어지는 원근 (각도 · 깊이)",
    f_gamba: "에이전트가 생각하는 동안 슬롯머신이 돎",
    f_detect: "감지됨 · 메시지 이동 · 완료 벨",
    f_focus: "젖빛 흐림 위에 창을 크게 미러링",
    f_restore: "충돌 / 종료 → 정확히 그 채팅 재개",
    f_mcp: "읽기 전용 관찰 + 푸시 · stdio, TCP 안 씀",
    scope_pane: "이 창",
    scope_outer: "외부",
    follow_outer: "외부 따르기",
    d_display: "GAUGES",
    g_text_size: "글자 크기",
    g_brightness: "밝기",
    g_contrast: "대비",
    g_colour: "색",
    g_text: "글자",
    g_background: "배경",
    g_gamma: "감마",
    g_menu_bar: "메뉴 바",
    g_warp: "곡면",
    d_reset: "초기화",
    d_roll: "롤",
    d_roll_spd: "롤 속도",
    d_roll_size: "롤 크기",
    d_roll_reset: "롤 → 테마별",
    d_crawl_hdr: "텍스트 크롤",
    d_crawl_on: "크롤 켜짐",
    d_crawl_off: "크롤 꺼짐",
    d_angle: "각도",
    d_depth: "깊이",
    k_alt_arrows: "Alt + 화살표",
    k_drag_subtab: "하위 탭 끌기",
    k_rclick_tab: "탭 우클릭",
    k_rclick: "우클릭",
    k_dbl_click: "더블 / 트리플 클릭",
    k_shift_ctrl_click: "Shift 또는 Ctrl 클릭",
    k_scroll_wheel: "스크롤 휠",
    k_theme_icon: "테마 아이콘 (우측 상단)",
    k_display_tray: "GAUGES tray",
    k_text_size_key: "A──A · Ctrl+휠",
    k_warp_dial: "곡면 다이얼",
    k_pane_header: "(창 헤더)",
    k_focus_inherit_key: "돋보기 · 테마 상속",
    k_wheel_key: "휠 / Shift+휠",
    k_input_colour: "당신의 입력 색",
    k_bell_finish: "완료 시 벨",
    k_mother_bar: "(마더 바)",
    kf_tiling: "타일 트리",
    kf_groups: "탭 그룹",
    kf_drag: "하위 탭 끌기",
    kf_rename: "리치 이름 변경",
    kf_popout: "팝아웃 스크래치",
    kf_themes: "4개 테마 + 커스텀",
    kf_perpane: "창별 외관",
    kf_wheel: "색상환",
    kf_grade: "모니터 보정",
    kf_warp: "배럴 곡면",
    kf_scan: "주사선 · 글로우",
    kf_crawl: "텍스트 크롤",
    kf_restore: "세션 복원",
    kf_mcp: "MCP 서버",
    t_theme: "DESIGN",
    t_wheel: "휠 · 핍을 끌어내기 · ◉ 시드 T 텍스트 C 보색",
    t_program: "프로그램 색",
    t_syntax: "구문",
    cm_ansi: "ansi",
    cm_mono: "모노",
    cm_theme: "테마",
    sc_off: "끄기",
    sc_code: "코드",
    sc_agentic: "에이전트",
    sc_logs: "로그",
    sc_mark: "마크",
    m_control: "제어",
    m_read_only: "읽기 전용",
    m_read_write: "읽기 + 쓰기",
    m_server_on: "서버 켜짐",
    m_server_off: "서버 꺼짐",
    m_expose: "노출:",
    exp_agents: "에이전트만",
    exp_all: "모든 창",
    m_events_on: "도구 호출 이벤트 스트리밍",
    m_events_off: "이벤트 꺼짐",
    m_writes_on: "쓰기 켜짐 · 에이전트가 재스타일 가능",
    m_writes_off: "쓰기 꺼짐 · 읽기 전용",
    m_theme_on: "테마 · 켜짐",
    m_theme_off: "테마 · 꺼짐",
    m_no_panes: "창 없음",
    m_exposed: "개 창 노출됨",
    m_watches: "에이전트 창 관찰 · PTY에 절대 쓰지 않음",
    m_transport: "라이브 서버 전송: 다음 단계",
    thm_quiet: "조용",
    thm_field: "필드",
    thm_tactical: "전술",
    thm_hacker: "해커",
    thm_gamba: "슬롯",
    thm_custom: "커스텀",
    focus_name: "돋보기",
    gamba_name: "슬롯",
    ch_split: "분할",
    ch_sub_terminal: "서브 터미널",
    st_tab: "탭",
    st_tabs: "탭",
    st_pane: "창",
    st_panes: "창",
    ch_ready: "준비됨",
    ph_live: "라이브",
    ph_exited: "종료됨",
    ph_done: "완료",
    ph_shell: "셸",
    ph_remote: "원격",
    dead_agents: "종료된 에이전트",
    resurrect: "되살리기",
    recoverable: "복구 가능",
    dead: "종료됨",
    no_recoverable: "복구할 수 있는 에이전트가 없습니다 \u{2014} 저장된 모든 세션은 실행 중이거나 이미 사라졌습니다.",
    dead_hint: "행을 클릭해 되살리거나 \u{2014} \u{2b07} .cdx로 컨텍스트를 이식 가능한 패키지로 내보내세요",
};

/// हिन्दी.
pub const HI: Strings = Strings {
    brand: "टर्मिनल आनंद",
    help: "मदद",
    shortcuts: "शॉर्टकट",
    features: "विशेषताएँ",
    demo_btn: "इस लेआउट का डेमो शुरू करें",
    demo_sub:
        "एक नई विंडो खोलता है जो इस लेआउट की नकल करती है, हर पेन डमी टेक्स्ट से भरा — स्क्रीन शेयर के लिए सुरक्षित",
    help_footer: "बंद करने के लिए Esc या बाहर क्लिक करें · थीम चलते समय संपादन योग्य TOML हैं",
    s_tabs: "टैब और पेन",
    s_edit: "संपादन और क्लिपबोर्ड",
    s_links: "लिंक",
    s_scroll: "स्क्रॉलबैक",
    s_look: "रूप",
    s_agents: "एजेंट · claude / codex",
    s_window: "विंडो",
    s_feat: "पेन · टैब · विंडो",
    s_theming: "थीम",
    s_crt: "CRT · गति",
    s_amcp: "एजेंट · MCP",
    new_tab: "नया टैब",
    switch_tabs: "टैब बदलें",
    move_tab: "टैब हटाएँ (समूह में / समूहों के बीच)",
    split: "विभाजित ↔ / ↕",
    move_focus: "पेन के बीच फ़ोकस ले जाएँ",
    drag_subtab: "ले जाएँ / विभाजित करें · बाहर खींचें = नई विंडो",
    rclick_tab: "नाम बदलें · रंग · समूह",
    rclick: "कॉपी · पेस्ट · लिंक खोलें · साफ़ करें",
    copy_paste: "कॉपी / पेस्ट",
    cut: "चयन काटें (इनपुट लाइन पर हटाता है)",
    find: "इस पेन में खोजें (फ़ज़ी) — ↵ वहाँ जाता है",
    find_all: "सभी पेन में खोजें (फ़ज़ी)",
    select_wl: "शब्द / पंक्ति चुनें",
    newline: "नई पंक्ति (claude/codex में बहु-पंक्ति)",
    open_link: "URL या फ़ाइल पथ खोलें",
    scroll_hist: "इतिहास स्क्रॉल करें",
    clear_scroll: "स्क्रॉलबैक साफ़ करें (Ctrl+L नहीं)",
    themes_wheel: "DESIGN — थीम और रंग चक्र",
    display_tray: "GAUGES — मॉनिटर समायोजन · टेक्स्ट आकार · टेक्स्ट-क्रॉल",
    text_size: "टेक्स्ट आकार",
    warp: "स्क्रीन मोड़ें (0 = सपाट → मछली का कटोरा)",
    jump_msg: "अपने पिछले / अगले संदेश पर जाएँ",
    nav_msg: "वही — अपने संदेशों में नेविगेट करें",
    focus: "लेंस — इस पेन को बड़ा मिरर करें",
    focus_inherit: "रीडर अपने पेन की तरह मुड़ता और चमकता है",
    pan_focus: "ज़ूम किए लेंस को नीचे / बग़ल में पैन करें",
    input_colour: "आपकी बारी अलग दिखती है (👤 व्हील पिप)",
    bell: "पेन ● पूर्ण + प्रति-एजेंट ध्वनि दिखाता है",
    mcp: "MCP — केवल-पढ़ने वाली एजेंट निगरानी सतह",
    new_window: "नई विंडो (त्वरित स्क्रैच)",
    f_tiling: "विभाजन केवल फ़ोकस किए पेन को बाँटते हैं",
    f_groups: "रंग पट्टी · हैंडल चिप · संक्षिप्त पिल",
    f_drag: "विभाजित करें, ले जाएँ या नई विंडो में अलग करें",
    f_rename: "टैब नामों में कर्सर, चयन, शब्द-नेविगेशन",
    f_popout: "त्वरित विंडो · एकल-इंस्टेंस जागरूक",
    f_themes: "चलते समय संपादन योग्य TOML, ~300ms हॉट रीलोड",
    f_perpane: "थीम और समायोजन विरासत में · 'बाहरी का अनुसरण'",
    f_wheel: "3 मार्कर — सीड · टेक्स्ट · पूरक",
    f_grade: "चमक/कंट्रास्ट/रंग/टेक्स्ट/पृष्ठभूमि/गामा + आकार",
    f_warp: "GPU वक्र · 0→1.5 डायल · प्रति-पेन",
    f_scan: "विग्नेट · फॉस्फर · ट्रैकिंग · कंपन",
    f_crawl: "स्टार वार्स शैली में पीछे जाता परिप्रेक्ष्य (कोण · गहराई)",
    f_gamba: "एजेंट सोचते समय स्लॉट मशीन घूमती है",
    f_detect: "पता चला · संदेश कूदें · पूर्ण घंटी",
    f_focus: "धुँधले कांच पर पेन को बड़ा मिरर करें",
    f_restore: "क्रैश / बंद → ठीक वही चैट फिर से शुरू करें",
    f_mcp: "केवल-पढ़ने वाली निगरानी + पुश · stdio, कभी TCP नहीं",
    scope_pane: "यह पेन",
    scope_outer: "बाहरी",
    follow_outer: "बाहरी का अनुसरण",
    d_display: "GAUGES",
    g_text_size: "टेक्स्ट आकार",
    g_brightness: "चमक",
    g_contrast: "कंट्रास्ट",
    g_colour: "रंग",
    g_text: "टेक्स्ट",
    g_background: "पृष्ठभूमि",
    g_gamma: "गामा",
    g_menu_bar: "मेन्यू बार",
    g_warp: "मोड़",
    d_reset: "रीसेट",
    d_roll: "रोल",
    d_roll_spd: "रोल गति",
    d_roll_size: "रोल आकार",
    d_roll_reset: "रोल → थीम अनुसार",
    d_crawl_hdr: "टेक्स्ट-क्रॉल",
    d_crawl_on: "क्रॉल चालू",
    d_crawl_off: "क्रॉल बंद",
    d_angle: "कोण",
    d_depth: "गहराई",
    k_alt_arrows: "Alt + तीर",
    k_drag_subtab: "उप-टैब खींचें",
    k_rclick_tab: "टैब पर दायाँ-क्लिक",
    k_rclick: "दायाँ-क्लिक",
    k_dbl_click: "डबल / ट्रिपल क्लिक",
    k_shift_ctrl_click: "Shift या Ctrl क्लिक",
    k_scroll_wheel: "स्क्रॉल व्हील",
    k_theme_icon: "थीम आइकन (ऊपर दाएँ)",
    k_display_tray: "GAUGES tray",
    k_text_size_key: "A──A · Ctrl+व्हील",
    k_warp_dial: "मोड़ डायल",
    k_pane_header: "(पेन हेडर)",
    k_focus_inherit_key: "लेंस · थीम विरासत",
    k_wheel_key: "व्हील / Shift+व्हील",
    k_input_colour: "आपके इनपुट का रंग",
    k_bell_finish: "समाप्ति पर घंटी",
    k_mother_bar: "(मदर बार)",
    kf_tiling: "टाइलिंग ट्री",
    kf_groups: "टैब समूह",
    kf_drag: "उप-टैब खींचें",
    kf_rename: "समृद्ध नाम बदलना",
    kf_popout: "पॉप-आउट स्क्रैच",
    kf_themes: "4 थीम + कस्टम",
    kf_perpane: "प्रति-पेन रूप",
    kf_wheel: "रंग चक्र",
    kf_grade: "मॉनिटर समायोजन",
    kf_warp: "बैरल मोड़",
    kf_scan: "स्कैनलाइन · चमक",
    kf_crawl: "टेक्स्ट-क्रॉल",
    kf_restore: "सत्र पुनर्स्थापना",
    kf_mcp: "MCP सर्वर",
    t_theme: "DESIGN",
    t_wheel: "चक्र · एक पिप बाहर खींचें · ◉ सीड T टेक्स्ट C पूरक",
    t_program: "प्रोग्राम रंग",
    t_syntax: "सिंटैक्स",
    cm_ansi: "ansi",
    cm_mono: "मोनो",
    cm_theme: "थीम",
    sc_off: "बंद",
    sc_code: "कोड",
    sc_agentic: "एजेंटिक",
    sc_logs: "लॉग",
    sc_mark: "मार्क",
    m_control: "नियंत्रण",
    m_read_only: "केवल पढ़ें",
    m_read_write: "पढ़ें + लिखें",
    m_server_on: "सर्वर चालू",
    m_server_off: "सर्वर बंद",
    m_expose: "दिखाएँ:",
    exp_agents: "केवल एजेंट",
    exp_all: "सभी पेन",
    m_events_on: "टूल-कॉल इवेंट स्ट्रीम करें",
    m_events_off: "इवेंट बंद",
    m_writes_on: "लेखन चालू · एजेंट पुनः स्टाइल कर सकते हैं",
    m_writes_off: "लेखन बंद · केवल पढ़ें",
    m_theme_on: "थीम · चालू",
    m_theme_off: "थीम · बंद",
    m_no_panes: "कोई पेन नहीं",
    m_exposed: "पेन दिखाए गए",
    m_watches: "एजेंट पेन देखता है · PTY में कभी नहीं लिखता",
    m_transport: "लाइव सर्वर ट्रांसपोर्ट: अगला चरण",
    thm_quiet: "शांत",
    thm_field: "फ़ील्ड",
    thm_tactical: "रणनीतिक",
    thm_hacker: "हैकर",
    thm_gamba: "स्लॉट",
    thm_custom: "कस्टम",
    focus_name: "लेंस",
    gamba_name: "स्लॉट",
    ch_split: "विभाजित",
    ch_sub_terminal: "सब-टर्मिनल",
    st_tab: "टैब",
    st_tabs: "टैब",
    st_pane: "पेन",
    st_panes: "पेन",
    ch_ready: "तैयार",
    ph_live: "लाइव",
    ph_exited: "बंद",
    ph_done: "पूर्ण",
    ph_shell: "शेल",
    ph_remote: "रिमोट",
    dead_agents: "मृत एजेंट",
    resurrect: "पुनर्जीवित करें",
    recoverable: "पुनर्प्राप्त करने योग्य",
    dead: "मृत",
    no_recoverable: "कोई पुनर्प्राप्त करने योग्य एजेंट नहीं \u{2014} हर सहेजा गया सत्र या तो सक्रिय है या पहले ही समाप्त हो चुका है।",
    dead_hint: "किसी पंक्ति पर क्लिक करके उसे पुनर्जीवित करें \u{2014} या \u{2b07} .cdx से उसके संदर्भ को एक पोर्टेबल पैकेज में सहेजें",
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_language_resolves_with_search_keys() {
        // each language has a non-empty autonym, English name, and code, and
        // resolves a string table — these three are the picker's fuzzy keys.
        let mut codes = std::collections::HashSet::new();
        for &l in &Lang::ALL {
            assert!(!l.native().is_empty(), "autonym");
            assert!(!l.english().is_empty(), "english name");
            assert_eq!(l.code().len(), 2, "two-letter code");
            assert!(codes.insert(l.code()), "codes must be unique: {}", l.code());
            let _ = l.strings();
        }
        assert_eq!(codes.len(), Lang::ALL.len());
        // the default language is the first in picker order
        assert_eq!(Lang::default(), Lang::ALL[0]);
    }

    #[test]
    fn english_is_the_source_strings() {
        // a couple of anchors so a careless edit to EN is caught
        assert_eq!(Lang::En.strings().new_tab, "New tab");
        assert_eq!(Lang::En.strings().help, "HELP");
    }
}
